runtime: nodejs
env: flex
# service: test
api_version: 1
instance_class: B1
manual_scaling:
  instances: 1
# [START env]
env_variables:
  SQL_USER: root
  SQL_PASSWORD: k30s2017G4
  SQL_DATABASE: sinfila_stg
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: sinfila-stg:us-east1:sinfila-stg
  SQL_CLIENT: mysql # either 'pg' or 'mysql' (all lowercase)
# [END env]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: sinfila-stg:us-east1:sinfila-stg
